config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'ui(/:action)', controller: 'ui'

  get '/home', to: 'pages#home'
  get '/about_us', to: 'pages#about_us'
  get '/privacy_policy', to: 'pages#privacy_policy'
  get '/delivery_information', to: 'pages#delivery_information'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/my_account', to: 'pages#my_account'
  get '/my_orders', to: 'pages#my_orders'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'

  resources :products , only: [:show] do
    collection do
      get '/search' , to: 'products#search'
    end
  end

  resources :categories, only: [:show]
  resources :sacred_symbols, only: [:show]

  namespace :admin do
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy, :show]
    resources :sacred_symbols , only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :edit, :update]
    resources :users, only: [:index, :update] do
      member do
        get '/orders', to: 'users#orders'
      end
    end
    get '/stock', to: 'products#stock'
    resources :products do
      member do
        patch '/stock', to: 'products#update_stock'
      end
    end
  end

  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'
  resources :users, only: [:update]

  get '/login', to: 'sessions#new'  
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/shopping_bag', to: 'user_shopping_bag_items#index'
  get '/wishlist', to: 'user_wishlist_items#index'

  resources :user_shopping_bag_items ,only: [:create, :update, :destroy]
  resources :user_wishlist_items ,only: [:create, :destroy]

  get '/checkout', to: 'orders#new'
  post '/checkout', to: 'orders#create'
  resources :orders, only: [:show] do
    collection do
      get '/terms_and_conditions', to: 'orders#terms_and_conditions'
    end
  end  
  get '/payment', to: 'orders#payment_new'
  post '/payment', to: 'orders#payment_create'

  get '/subregion_options' => 'orders#subregion_options'

  post "/orders/:slug" => "orders#payment_show"
  post "/paypal_hook" => "orders#paypal_hook"

end

app/models/order.rb
class Order <ActiveRecord::Base
  include Sluggable
  sluggable_column :slug_column

  validates_presence_of :first_name , :last_name, :address_line1, :city, :country_code, :phone_number, :postal_code, :email  
  has_many :user_shopping_bag_items, as: :position
  has_many :shopping_bag_items, through: :user_shopping_bag_items, source: :product
  belongs_to :user

  def slug_column
    first_name + last_name
  end

  def total_bill
    user_shopping_bag_items.map(&:total_price).inject(0, :+)
  end

  def update_stock
    user_shopping_bag_items.each do |shopping_bag_item|
      shopping_bag_item.product.update(stock: shopping_bag_item.product.stock - shopping_bag_item.qty)
    end
  end

  def self.last_orders
    Order.where("status LIKE ? ", 'paid%').order('updated_at') + Order.where("status LIKE ? ", 'sent').order('updated_at DESC')
  end

  def paypal_url(return_path)
    values = {
        business: "maya166-facilitator@gmail.com",
        cmd: "_xclick",
        upload: 1,
        return: "#{Rails.application.secrets.app_host}#{return_path}",
        invoice: id,
        amount: 10000,
        item_name: "maya",
        item_number: 1,
        quantity: '1',
        notify_url: "#{Rails.application.secrets.app_host}/paypal_hook"
    }
    "#{Rails.application.secrets.paypal_host}/cgi-bin/webscr?" + values.to_query
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController <AdminController

  def index
    @orders = Order.last_orders
  end

  def edit
    @order = Order.find_by(slug: params[:id])
  end

  def update
    @order = Order.find_by(slug: params[:id])
    if @order.update(status: 'sent', confirmation_number: params[:confirmation_number], tracking_number: params[:tracking_number])
      ApplicationMailer.order_delivary_approval(@order).deliver
      flash[:notice] = "Package was updated"
      redirect_to admin_orders_path
    else
      flash[:error] = "Package number is invalid"
      render :edit
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController <ApplicationController

  before_filter do
    locale = params[:locale]
    Carmen.i18n_backend.locale = locale if locale
  end

  def subregion_options
    render partial: 'subregion_select'
  end

  def show
    @order = Order.find_by(slug: params[:id])
    if ! (logged_in? && ( (@order.user && @order.user == current_user) || current_user_admin?))
      flash[:error] = "Error: Require login"
      redirect_to :back
    end 
  end

  def new
    if shopping_bag.empty?
      flash[:notice] = "Your Shopping Bag Is Empty.."
      redirect_to :back
    else
      @order = Order.new
      respond_to do |format|
        format.html 
        format.json { render json: @order }
      end
    end
  end

  def terms_and_conditions
    respond_to do |format|
      format.html
      format.js
    end 
  end

  def create
    @order = Order.new(order_params, user: logged_in? ? current_user : nil)
    if @order.valid?
      if !params[:accept_terms_and_conditions]
        flash[:error] = "Please confirm that i have read and agree with the Terms and Conditions."
        render :new
      else
        if !check_shopping_bag_stock
          render :new
        else
          session[:order_attributes] = @order.attributes 
          redirect_to '/payment'
        end
      end
    else
      render :new  
    end
  end

  def payment_new
    if shopping_bag.empty?
      flash[:notice] = "Your Shopping Bag Is Empty.."
      redirect_to :back
    end
    @order = Order.new(session[:order_attributes])
  end

  def payment_create
    @order = Order.new(session[:order_attributes])
    if check_shopping_bag_stock == true 
      charge = StripeWrapper::Charge.create(
        :card => params[:stripeToken],
        :amount => total_bill,
        :description => "order nu 12"
      )
      if charge.successful?
        @order.reference_id = charge.id
        handle_order(@order, 'stripe')
      else
        flash[:error] =  charge.error_message
        render :payment_new
      end
    else
      render :payment_new
    end
  end

    protect_from_forgery except: [:paypal_hook]

    def paypal_hook
      binding.pry
      params.permit! # Permit all Paypal input params
      status = params[:payment_status]
      if status == "Completed"
        @order = Order.new(session[:order_attributes])
        handle_order(@order,'paypal')
      else
        render nothing: true
      end  
    end

  private

  def order_params
    params.require(:order).permit(:first_name,:last_name,:address_line1,:address_line2,:city,:country_code,:state_code,:postal_code,:phone_number,:email)
  end

  def check_shopping_bag_stock  
    all_in_stock = true
    shopping_bag.each do |shopping_bag_item|
      in_stock = shopping_bag_item.product.stock
      if in_stock <  shopping_bag_item.qty
        if logged_in?
          shopping_bag_item.update(qty: in_stock)
        else
          i = session[:guest_shopping_bag_item].index(shopping_bag_item.id.to_s)
          session[:guest_shopping_bag_item_qty][i] = in_stock.to_s
        end
        flash[:error] = "Product #{shopping_bag_item.name} is now available only #{in_stock} times, your order was updated.."
        all_in_stock = false
      end     
    end
    return all_in_stock 
  end

  def add_shopping_bag_items_to_order(order)

    if logged_in?
      shopping_bag.each do |shopping_bag_item|
        shopping_bag_item.update(position: order)      
      end
    else
      shopping_bag.each do |shopping_bag_item|
        UserShoppingBagItem.create(product: shopping_bag_item.product, qty: shopping_bag_item.qty, position: order)
      end
      session[:guest_shopping_bag_item] = []
      session[:guest_shopping_bag_item_qty] = []
    end
  end

  def handle_order(order, payment_method) 
    order.status = 'paid with ' + payment_method
    order.user = current_user unless !logged_in?
    order.save
    order.update_stock
    add_shopping_bag_items_to_order(order)
    ApplicationMailer.order_approval(order).deliver
    session[:order_attributes] = nil
    flash[:notice] =  "Payment was made."
    redirect_to root_path
  end
end

app/views/admin/orders/_orders.html.haml
.table-responsive.admin-table
  %table.table.table-bordered
    %thead
      %tr
        %td.text-center
          User
        %td.text-center
          Date
        %td.text-center
          Amount
        %td.text-center
          Order
        %td.text-center
    %tbody
      - @orders.each do |order|
        %tr
          %td.text-center
            - if order.user
              = link_to order.user.name, user_path(order.user)
            - else
              Guese            
          %td.text-center
            = display_date(order.created_at)
          %td.text-center
            = display_price(order.total_bill)
          %td.text-center
            = link_to 'Show Order', edit_admin_order_path(order) 
          %td.text-center
            - if order.status == 'sent'
              = link_to edit_admin_order_path(order) , class: 'btn btn-sent tool-tip' do
                Sent
            - else
              = link_to edit_admin_order_path(order) , class: 'btn btn-send tool-tip' do
                Send

app/views/admin/orders/edit.html.haml
%section
  .row
    .col-sm-6.col-xs-12
      .admin-table-title  
        Customer Details
      .order-col
        %ul.list-unstyled
          %li
            %span.field-name
              First Name:
            %span.field    
              = @order.first_name 
          %li
            %span.field-name
              Last Name:
            %span.field    
              = @order.last_name  
          %li
            %span.field-name
              Address Line1:
            %span.field    
              = @order.address_line1
          %li
            %span.field-name
              Address Line2:
            %span.field    
              = @order.address_line2
          %li
            %span.field-name
              City:
            %span.field    
              = @order.city       
          %li
            %span.field-name
              Country:
            %span.field    
              = display_country(@order.country_code)
          %li
            %span.field-name
              State:
            %span.field    
              = display_state(@order.country_code, @order.state_code)
          %li
            %span.field-name
              Postal Code:
            %span.field    
              = @order.postal_code             
          %li
            %span.field-name
              Phone Number:
            %span.field    
              = @order.phone_number
          %li
            %span.field-name
              Email:
            %span.field    
              = @order.email
          - if @order.status == 'paid' 
            %li
              .field
                * The Order was maded at #{display_date(@order.updated_at)} 
            %li
              .field   
                Fill after sending the package:
            = form_tag  admin_order_path(@order), method: :patch do
              %li
                .row.input-row
                  .col-xs-5
                    .field-name
                      Confirmation Number:
                  .col-xs-5
                    = number_field_tag  :confirmation_number, nil, class: 'form-control'
              %li    
                .row    
                  .col-xs-5
                    .field-name
                      Tracking Number:
                  .col-xs-5
                    = number_field_tag :tracking_number, nil, class: 'form-control'                 
                .row  
                  .col-xs-2
                    = submit_tag 'Send', class: 'btn btn-sent tool-tip'
          - else
            %li
              .field
                * The Order was sent at:  #{display_date(@order.updated_at)}
            %li
              %span.field-name
                Confirmation Number:
              %span.field
                = @order.confirmation_number
            %li     
              %span.field-name
                Tracking Number:
              %span.field
                = @order.tracking_number        
    .col-sm-6.col-xs-12
      .admin-table-title  
        Order Summary  
      .table-responsive.admin-table
        %table.table.table-bordered
          %thead
            %tr
              %td.text-center
                Image
              %td.text-center
                Product
              %td.text-center
                Qty
              %td.text-center
                Paid
          %tbody
            - @order.user_shopping_bag_items.each do |user_shopping_bag_item| 
              %tr
                %td.text-center
                  %img.img-responsive{:alt => "image", :src => user_shopping_bag_item.image.big_thumb, :title => "image"}/
                %td.text-center
                  = link_to user_shopping_bag_item.name, product_path(user_shopping_bag_item.product) 
                %td.text-center 
                  x #{user_shopping_bag_item.qty}
                %td.text-center 
                  #{display_price(user_shopping_bag_item.price)}            

app/views/admin/orders/index.html.haml
.admin-table-title
  Orders  
= render 'orders'