config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'ui(/:action)', controller: 'ui'

  get '/home', to: 'pages#home'
  get '/about_us', to: 'pages#about_us'
  get '/privacy_policy', to: 'pages#privacy_policy'
  get '/delivery_information', to: 'pages#delivery_information'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/my_account', to: 'pages#my_account'
  get '/my_orders', to: 'pages#my_orders'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'

  resources :products , only: [:show] do
    collection do
      get '/search' , to: 'products#search'
    end
  end

  resources :categories, only: [:show]
  resources :sacred_symbols, only: [:show]

  namespace :admin do
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy, :show]
    resources :sacred_symbols , only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :edit, :update]
    resources :users, only: [:index, :update] do
      member do
        get '/orders', to: 'users#orders'
      end
    end
    get '/stock', to: 'products#stock'
    resources :products do
      member do
        patch '/stock', to: 'products#update_stock'
      end
    end
  end

  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'
  resources :users, only: [:update]

  get '/login', to: 'sessions#new'  
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/shopping_bag', to: 'user_shopping_bag_items#index'
  get '/wishlist', to: 'user_wishlist_items#index'

  resources :user_shopping_bag_items ,only: [:create, :update, :destroy]
  resources :user_wishlist_items ,only: [:create, :destroy]

  get '/checkout', to: 'orders#new'
  post '/checkout', to: 'orders#create'
  resources :orders, only: [:show] do
    collection do
      get '/terms_and_conditions', to: 'orders#terms_and_conditions'
    end
  end  
  get '/payment', to: 'orders#payment_new'
  post '/payment', to: 'orders#payment_create'

  get '/subregion_options' => 'orders#subregion_options'

  post "/orders/:slug" => "orders#payment_show"
  post "/paypal_hook" => "orders#paypal_hook"

end

app/views/shared/_admin_menu.html.haml
.admin-menu
  .hidden-xs.hidden-sm
    %h3.side-heading Administration
    .list-group
      = link_to admin_orders_path, class: (nav_active(admin_orders_path) + ' list-group-item') do
        %i.fa.fa-bell{:title => "Orders"}
        %span
          Orders
      = link_to admin_stock_path, class: (nav_active(admin_stock_path) + ' list-group-item') do 
        %i.fa.fa-flag{:title => "Stock"}
        %span
          Stock 
      = link_to admin_users_path, class: (nav_active(admin_users_path) + ' list-group-item') do
        %i.fa.fa-user{:title => "Users"}
        %span
          Users
      = link_to 'Products', admin_products_path , class: (nav_active(admin_products_path) + ' list-group-item')      
      - Category.all.each do |category|
        = link_to admin_category_path(category), class: (nav_active(admin_category_path(category)) + ' list-group-item')  do
          %i.fa.fa-chevron-right
          = category.name
      = link_to 'Categories', admin_categories_path, class: (nav_active(admin_categories_path) + ' list-group-item')
      = link_to 'Sacred Symbols', admin_sacred_symbols_path, class: (nav_active(admin_sacred_symbols_path) + ' list-group-item')
      / Nav Header Starts
  .visible-xs-block.visible-sm-block    
    .navbar-header.admin-menu-toggle-button
      Administrasion Menu
      %button.btn.btn-navbar.navbar-toggle{"data-target" => ".navbar-admin-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle Navigation
        %i.fa.fa-bars
    / Nav Header Ends
    / Navbar Cat collapse Starts
    .collapse.navbar-collapse.navbar-admin-collapse
      .list-group
        = link_to admin_orders_path, class: (nav_active(admin_orders_path) + ' list-group-item') do
          %i.fa.fa-bell{:title => "Orders"}
          %span
            Orders
        = link_to admin_stock_path, class: (nav_active(admin_stock_path) + ' list-group-item') do 
          %i.fa.fa-flag{:title => "Stock"}
          %span
            Stock 
        = link_to admin_users_path, class: (nav_active(admin_users_path) + ' list-group-item') do
          %i.fa.fa-user{:title => "Users"}
          %span
            Users
        = link_to 'Products', admin_products_path , class: (nav_active(admin_products_path) + ' list-group-item')      
        - Category.all.each do |category|
          = link_to admin_category_path(category), class: (nav_active(admin_category_path(category)) + ' list-group-item')  do
            %i.fa.fa-chevron-right
            = category.name
        = link_to 'Categories', admin_categories_path, class: (nav_active(admin_categories_path) + ' list-group-item')
        = link_to 'Sacred Symbols', admin_sacred_symbols_path, class: ( nav_active(admin_sacred_symbols_path) + ' list-group-item')
  / Navbar Cat collapse Ends

app/views/shared/_footer.html.haml
%footer#footer-area
  / Footer Links Starts
  .footer-links
    / Container Starts
    .container
      / Information Links Starts
      .col-md-2.col-sm-6
        %h5 Information
        %ul
          %li
            = link_to 'About Us', about_us_path
          %li
            = link_to 'Delivery Information', delivery_information_path
          %li
            = link_to 'Terms & Conditions', terms_and_conditions_path  
          %li
            = link_to 'Privacy Policy', privacy_policy_path
      / Information Links Ends
      / My Account Links Starts
      .col-md-2.col-sm-6
        %h5 My Account
        %ul
          %li
            = link_to 'My Acount Info', my_account_path
          %li
            = link_to 'My Orders', my_orders_path 
      / My Account Links Ends
      / Customer Service Links Starts
      .col-md-2.col-sm-6
        %h5 Service
        %ul
          %li
            = link_to 'Contact Us', contact_us_path
          %li
            %a{:href => "#"} Returns
          %li
            %a{:href => "#"} Site Map
          %li
            %a{:href => "#"} Affiliates
          %li
            %a{:href => "#"} Specials
      / Customer Service Links Ends
      / Follow Us Links Starts
      .col-md-2.col-sm-6
        %h5 Follow Us
        %ul
          %li
            %a{:href => "#"} Facebook
          %li
            %a{:href => "#"} Twitter
          %li
            %a{:href => "#"} RSS
          %li
            %a{:href => "#"} YouTube
      / Follow Us Links Ends
      / Contact Us Starts
      .col-md-4.col-sm-12.last
        %h5 Contact Us
        %ul
          %li My Company
          %li
            1247 LB Nagar Road, Hyderabad, Telangana - 35
          %li
            Email:
            %a{:href => "#"} info@demolink.com
        %h4.lead
          Tel:
          %span 1(234) 567-9842
      / Contact Us Ends
    / Container Ends
  / Footer Links Ends
  / Copyright Area Starts
  .copyright
    / Container Starts
    .container
      / Starts
      %p.pull-left
        \  2014 Spice Shoppe Stores. Bootstrap Layout All Rights Reserved. Designed By
        %a{:href => "http://sainathchillapuram.com"} Sainath Chillapuram
      / Ends
      / Payment Gateway Links Starts
      %ul.pull-right.list-inline
        %li
          %img{:alt => "PaymentGateway", :src => "/images/payment-icon/cirrus.png"}/
        %li
          %img{:alt => "PaymentGateway", :src => "/images/payment-icon/paypal.png"}/
        %li
          %img{:alt => "PaymentGateway", :src => "/images/payment-icon/visa.png"}/
        %li
          %img{:alt => "PaymentGateway", :src => "/images/payment-icon/mastercard.png"}/
        %li
          %img{:alt => "PaymentGateway", :src => "/images/payment-icon/americanexpress.png"}/
      / Payment Gateway Links Ends
    / Container Ends
  / Copyright Area Ends

app/views/shared/_head.html.haml
%title Cosmic Pendants Online Shop
%meta(charset="UTF-8")
%meta(name="viewport" content="width=device-width, initial-scale=1.0")
%meta{:content => "initial-scale=1", :name => "viewport"}/
= favicon_link_tag '/favicon.ico'
= csrf_meta_tag
= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
= javascript_include_tag "application", "data-turbolinks-track" => true
/ Google Web Fonts
%link{:href => "https://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,700italic,400,300,700", :rel => "stylesheet", :type => "text/css"}/
%link{:href => "https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800", :rel => "stylesheet", :type => "text/css"}/
/ Fav and touch icons
%link{:href => "images/fav-144.png", :rel => "apple-touch-icon-precomposed", :sizes => "144x144"}/
%link{:href => "images/fav-114.png", :rel => "apple-touch-icon-precomposed", :sizes => "114x114"}/
%link{:href => "images/fav-72.png", :rel => "apple-touch-icon-precomposed", :sizes => "72x72"}/
%link{:href => "images/fav-57.png", :rel => "apple-touch-icon-precomposed"}/
/ %link{:href => "images/fav.png", :rel => "shortcut icon"}/
= render 'shared/modals'

app/views/shared/_header.html.haml
%header#header-area
  / Header Top Starts
  .header-top
    .container
      / Header Links Starts
      .col-sm-3.col-md-2
        - if logged_in? && current_user_admin?
          = link_to 'Administration', admin_orders_path, class: 'btn shopping-bag-checkout-btn'          
      .col-md-8.col-md-offset-2.col-sm-8.col-sm-offset-1.col-xs-12
        .header-links
          %ul.nav.navbar-nav.pull-right
            %li
              = link_to root_path do
                %i.fa.fa-home{:title => "Home"}
                %span.hidden-sm.hidden-xs
                  Home
            %li{:class => nav_active(wishlist_path)}
              = link_to wishlist_path do
                %i.fa.fa-heart{:title => "Wish List"}
                %span.hidden-sm.hidden-xs
                  Wish List(#{wishlist_count})
            %li{:class => nav_active(checkout_path)}
              = link_to checkout_path do
                %i.fa.fa-check{:title => "Checkout"}
                %span.hidden-sm.hidden-xs
                  Checkout
            - if logged_in?       
              %li{:class => nav_active(my_account_path)}
                = link_to my_account_path do
                  %i.fa.fa-user{:title => "My Account"}
                  %span.hidden-sm.hidden-xs
                    My Account            
              %li      
                = link_to logout_path, method: :delete  do
                  %i.fa.fa-lock{:title => "Login"}
                  %span.hidden-sm.hidden-xs
                    LogOut      
            - else             
              %li
                = link_to sign_up_path, remote: true do
                  %i.fa.fa-lock{:title => "Sign Up"}
                  %span.hidden-sm.hidden-xs
                    Sign Up       
              %li
                = link_to login_path, remote: true do
                  %i.fa.fa-lock{:title => "Login"}
                  %span.hidden-sm.hidden-xs
                    Login              
      / Header Links Ends
  / Header Top Ends
  / Starts
  .container
    / Main Header Starts
    .main-header
      .row
        / Logo Starts
        .col-md-9
          #logo
            = link_to home_path do
              %img.img-responsive{:alt => "Cosmic Pendants", :src => "/images/logo.png", :title => "Cosmic Pendants"}/
        / Logo End
        / Shopping Bag Starts
        .col-md-3.col-md-offset-0.col-sm-5.col-sm-offset-7.shopping-bag-block
          #bag.btn-group.btn-block
            %button.btn.btn-block.btn-lg.dropdown-toggle.dropdown-toggle-shopping-bag{"data-toggle" => "dropdown", :type => "button"}
              %img.shopping-bag{:alt => "Shopping Bag", :src => '/images/shopping_bag.png' }
              Shopping Bag:
              %span#bag-total #{shopping_bag.count} item(s) - #{display_price(total_bill)}
              %i.fa.fa-caret-down
            %ul.dropdown-menu
              = render 'user_shopping_bag_items/shopping_bag_summary'
        / Shopping Bag Ends
    / Main Header Ends
    / Main Menu Starts
    %nav#main-menu.navbar{:role => "navigation"}
      / Nav Header Starts
      .navbar-header
        %button.btn.btn-navbar.navbar-toggle{"data-target" => ".navbar-cat-collapse", "data-toggle" => "collapse", :type => "button"}
          %span.sr-only Toggle Navigation
          %i.fa.fa-bars
      / Nav Header Ends
      / Navbar Cat collapse Starts
      .collapse.navbar-collapse.navbar-cat-collapse
        .row
          .col-sm-9
            %ul.nav.navbar-nav
              - Category.all.each do |category|
                %li{:class => nav_active(category_path(category))}
                  = link_to category.name, category_path(category)
              %li.dropdown
                %a.dropdown-toggle.dropdown-toggle-sacred-symbols{"data-delay" => "10", "data-hover" => "dropdown", "data-toggle" => "dropdown"}
                  Sacred Symbols
                %ul.dropdown-menu{:role => "menu"}
                  -SacredSymbol.all.each do |sacred_symbol|
                    = link_to sacred_symbol_path(sacred_symbol), class: (nav_active(sacred_symbol_path(sacred_symbol)) + ' symbol-list-group-item list-group-item') do
                      %li
                        .row
                          .col-sm-3.col-xs-5
                            %img.symbols-menu-image{:alt => sacred_symbol.name, :src => sacred_symbol.image.small_thumb}/
                          .col-sm-9.col-xs-7.symbols-menu-text  
                            = sacred_symbol.name
            / Search Starts
          .col-sm-3  
            #search  
              = form_tag(search_products_path, method: "get") do            
                .input-group
                  = text_field_tag :search_term, params[:search_term], :placeholder => "Search Store",class: "form-control input-lg"  
                  %span.input-group-btn
                    = button_tag nil , class: "btn btn-lg" do
                      %i.fa.fa-search        
            / Search Ends
      / Navbar Cat collapse Ends
    / Main Menu Ends
  / Ends

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
	%div(class="alert alert-#{name}")
		%a.close(data-dismiss='alert') &#215;
		= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_modals.html.haml
/ Modal
#user-modal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "registerModalLabel", :role => "dialog", :tabindex => "-1"}
%button.btn.btn-primary.btn-lg{"data-target" => "#user-modal", "data-toggle" => "modal", :type => "button", :id => 'open-modal', :style => "display: none;"}   

app/views/shared/_sidebar.html.haml
- 3.times do
  .image    
    %img.img-responsive{:alt => "adds", :src => "/images/add.png"}