config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'ui(/:action)', controller: 'ui'

  get '/home', to: 'pages#home'
  get '/about_us', to: 'pages#about_us'
  get '/privacy_policy', to: 'pages#privacy_policy'
  get '/delivery_information', to: 'pages#delivery_information'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/my_account', to: 'pages#my_account'
  get '/my_orders', to: 'pages#my_orders'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'

  resources :products , only: [:show] do
    collection do
      get '/search' , to: 'products#search'
    end
  end

  resources :categories, only: [:show]
  resources :sacred_symbols, only: [:show]

  namespace :admin do
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy, :show]
    resources :sacred_symbols , only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :edit, :update]
    resources :users, only: [:index, :update] do
      member do
        get '/orders', to: 'users#orders'
      end
    end
    get '/stock', to: 'products#stock'
    resources :products do
      member do
        patch '/stock', to: 'products#update_stock'
      end
    end
  end

  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'
  resources :users, only: [:update]

  get '/login', to: 'sessions#new'  
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/shopping_bag', to: 'user_shopping_bag_items#index'
  get '/wishlist', to: 'user_wishlist_items#index'

  resources :user_shopping_bag_items ,only: [:create, :update, :destroy]
  resources :user_wishlist_items ,only: [:create, :destroy]

  get '/checkout', to: 'orders#new'
  post '/checkout', to: 'orders#create'
  resources :orders, only: [:show] do
    collection do
      get '/terms_and_conditions', to: 'orders#terms_and_conditions'
    end
  end  
  get '/payment', to: 'orders#payment_new'
  post '/payment', to: 'orders#payment_create'

  get '/subregion_options' => 'orders#subregion_options'

  post "/orders/:slug" => "orders#payment_show"
  post "/paypal_hook" => "orders#paypal_hook"

end

app/models/product.rb
class Product <ActiveRecord::Base
  include Sluggable
  sluggable_column :name
  
  belongs_to :category
  has_many :product_symbols
  has_many :sacred_symbols, through: :product_symbols
  validates_presence_of :name , :description, :category, :price, :image
  mount_uploader :image, ProductImageUploader
  validates_numericality_of :stock, {only_integer: true, greater_than_or_equal_to: 0}
  validates_numericality_of :price, {only_integer: true, greater_than_or_equal_to: 100}

  has_many :user_shopping_bag_items
 
  has_many :user_wishlist_items
  has_many :wishlisted_users, through: :user_wishlist_items, source: :user

  before_save :capitalize_name

  def capitalize_name
    self.name = self.name.titleize
  end

  def self.search_by_name(search_term)
    return [] if search_term.blank?
    Product.where("name ILIKE ? ", "%#{search_term}%")
  end 

  def last_ordered
    orders.last.updated_at unless orders.empty?
  end

  def orders
    user_shopping_bag_items.where("position_type ILIKE ? ", Order).order('updated_at')
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController <AdminController

  def index
    @product = Product.new
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "#{@product.name} was added"
      redirect_to admin_products_path
    else
      flash[:error] = "The product #{@product.name} was NOT added"
      @products = Product.all
      render :index
    end  
  end

  def edit
    @product = Product.find_by(slug: params[:id])
    @products = Product.all
    render :index
  end

  def update
    @product = Product.find_by(slug: params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = "#{@product.name} was updated"
      redirect_to admin_products_path
    else
      flash[:error] = "#{@product.name} was NOT updated"
      @products = Product.all
      render :index
    end
  end

  def destroy
    product = Product.find_by(slug: params[:id])
    product.delete
    flash[:notice] = "#{product.name} was deleted"
    redirect_to admin_products_path
  end

  def stock
    @products = Product.all.order('stock')
  end

  def update_stock
    @product = Product.find_by(slug: params[:id])
    if @product.update(stock: params[:stock])
      flash[:notice] = "#{@product.name} stock was updated"
    else
      flash[:error] = "Error: #{@product.name} stock was NOT updated"
    end
    @products = Product.all.order('stock')
    render :stock

  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :category_id, :description, :image, :stock, :sacred_symbol_ids => [])
  end

end

app/controllers/products_controller.rb
class ProductsController <ApplicationController

  def show
    @product = Product.find_by(slug: params[:id])
    @related_products = Product.all
  end

  def search
    @products = Product.search_by_name(params[:search_term]) 
    SacredSymbol.search_by_name(params[:search_term]).each do |sacred_symbol|
      @products += sacred_symbol.products.drop_while { |item| @products.include?(item) } 
    end
    Category.search_by_name(params[:search_term]).each do |category|
      @products += category.products.drop_while { |item| @products.include?(item) } 
    end
  end

end

app/views/admin/products/_form.html.haml
.panel.panel-smart
  .panel-heading
    %h3.panel-title
      = @product.new_record? ? 'Add New Product' : 'Update Product Details'
  .panel-body    
    = bootstrap_form_for [:admin, @product], layout: :horizontal do |f|
      .col-sm-6.col-xs-12
        .admin-product-form-row
          = f.text_field :name, label: 'Name:', placeholder: 'Product Name', label_col: "col-sm-3", control_col: "col-sm-7"
        .admin-product-form-row
          = f.select :category_id,  options_for_select(Category.all.map {|category| [category.name, category.id]}, f.object.category_id),label: 'Category:', label_col: "col-sm-3", control_col: "col-sm-6"
        .admin-product-form-row
          = f.file_field :image, label: 'Picture:',label_col: "col-sm-3", control_col: "col-sm-7"
        .admin-product-form-row
          .form-group
            %label.control-label.col-sm-4{:for => "product_price"} Price In &cent:
            .col-sm-4
              %input.form-control{:name => 'product[price]', :id => 'product_price', :value => @product.price,:placeholder => "CENTS!!!", :type => "text", :size => "6"}/
        .admin-product-form-row
          = f.text_field :stock, label: 'Qty In Stock:',label_col: "col-sm-4", control_col: "col-sm-4"    
      .col-sm-6.col-xs-12  
        .admin-product-form-row
          = f.collection_check_boxes :sacred_symbol_ids,SacredSymbol.all, :id, :name , label: 'Symbols:', inline: true, label_col: "col-sm-3", control_col: "col-sm-9"
        = f.text_area :description, label: 'Description:', label_col: "col-sm-3", control_col: "col-sm-9", rows: '6'  
      .col-sm-12.col-xs-12  
        = f.submit @product.new_record? ? 'Add Product' : 'Update Details', class: "btn btn-add" , id: 'product-form-submit'

app/views/admin/products/_products.html.haml
- @products.each  do |product|
  .product-col
    .row
      .col-md-2.col-sm-3.col-xs-3
        .image
          %img.img-responsive{:src => product.image}
      .visible-xs-block.col-xs-9
        %br
        %h4
          =link_to product.name   
      .col-md-10.col-sm-9.col-xs-12
        %h4.hidden-xs
          =link_to product.name
        %table
          %tr
            %th Category:
            %td 
              = link_to product.category.name, admin_category_path(product.category)
          %tr
            %th Price:
            %td 
              = display_price(product.price)
          %tr
            %th stock:
            %td 
              #{product.stock} Items In Stock              
          %tr
            %th Simbols:
            %td 
              - product.sacred_symbols.each do |sacred_symbol|
                = link_to sacred_symbol.name , sacred_symbol_path(sacred_symbol)
                ,
          %tr
            %th Description:
            %td 
              = product.description     
          %tr
            %th Orders:
            %td 
              = link_to nil, '5643 orders'             
        .bag-button.button-group
          = link_to 'Update',edit_admin_product_path(product), class: 'btn btn-update'
          = link_to admin_product_path(product), method: :delete, class: 'btn btn-remove' do
            Delete Product
            %i.fa.fa-remove 

app/views/admin/products/index.html.haml
.row 
  .col-md-12   
    = render 'form'
.admin-table-title  
  All Product       
= render 'products'

app/views/admin/products/stock.html.haml
.admin-table-title
  Stock  
.row
  .col-md-10  
    .table-responsive.admin-table
      %table.table.table-bordered
        %thead
          %tr
            %td.text-center(width="12%")
              Image
            %td.text-center
              Name 
            %td.text-center(width="10%")
              Orders  
            %td.text-center(width="10%")
              Last Sell   
            %td.text-center(width="10%")
              In Stock    
            %td.text-center(width="10%")            
        %tbody
          - @products.each do |product|
            =  form_tag  stock_admin_product_path(product), method: :patch do
              %tr
                %td.text-center
                  %img.img-responsive{:alt => "image", :src => product.image.big_thumb, :title => "image"}/
                %td.text-center
                  =link_to product.name, product
                %td.text-center
                  = product.orders.count
                %td.text-center
                  = display_date(product.last_ordered)     
                %td.text-center
                  .input-group.btn-block
                    = number_field_tag 'stock', product.stock, class: 'form-control', min: 0, size: '1'
                %td.text-center
                  = submit_tag 'Update Stock', class: 'btn btn-default tool-tip'
                    