config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get 'ui(/:action)', controller: 'ui'

  get '/home', to: 'pages#home'
  get '/about_us', to: 'pages#about_us'
  get '/privacy_policy', to: 'pages#privacy_policy'
  get '/delivery_information', to: 'pages#delivery_information'
  get 'terms_and_conditions', to: 'pages#terms_and_conditions'
  get '/my_account', to: 'pages#my_account'
  get '/my_orders', to: 'pages#my_orders'

  get '/contact_us', to: 'contact_us#new'
  post '/contact_us', to: 'contact_us#create'

  resources :products , only: [:show] do
    collection do
      get '/search' , to: 'products#search'
    end
  end

  resources :categories, only: [:show]
  resources :sacred_symbols, only: [:show]

  namespace :admin do
    resources :products, only: [:index, :create, :edit, :update, :destroy]
    resources :categories, only: [:index, :create, :edit, :update, :destroy, :show]
    resources :sacred_symbols , only: [:index, :create, :edit, :update, :destroy]
    resources :orders, only: [:index, :edit, :update]
    resources :users, only: [:index, :update] do
      member do
        get '/orders', to: 'users#orders'
      end
    end
    get '/stock', to: 'products#stock'
    resources :products do
      member do
        patch '/stock', to: 'products#update_stock'
      end
    end
  end

  get '/sign_up', to: 'users#new'
  post '/sign_up', to: 'users#create'
  resources :users, only: [:update]

  get '/login', to: 'sessions#new'  
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/shopping_bag', to: 'user_shopping_bag_items#index'
  get '/wishlist', to: 'user_wishlist_items#index'

  resources :user_shopping_bag_items ,only: [:create, :update, :destroy]
  resources :user_wishlist_items ,only: [:create, :destroy]

  get '/checkout', to: 'orders#new'
  post '/checkout', to: 'orders#create'
  resources :orders, only: [:show] do
    collection do
      get '/terms_and_conditions', to: 'orders#terms_and_conditions'
    end
  end  
  get '/payment', to: 'orders#payment_new'
  post '/payment', to: 'orders#payment_create'

  get '/subregion_options' => 'orders#subregion_options'

  post "/orders/:slug" => "orders#payment_show"
  post "/paypal_hook" => "orders#paypal_hook"

end

app/models/product.rb
class Product <ActiveRecord::Base
  include Sluggable
  sluggable_column :name
  
  belongs_to :category
  has_many :product_symbols
  has_many :sacred_symbols, through: :product_symbols
  validates_presence_of :name , :description, :category, :price, :image
  mount_uploader :image, ProductImageUploader
  validates_numericality_of :stock, {only_integer: true, greater_than_or_equal_to: 0}
  validates_numericality_of :price, {only_integer: true, greater_than_or_equal_to: 100}

  has_many :user_shopping_bag_items
 
  has_many :user_wishlist_items
  has_many :wishlisted_users, through: :user_wishlist_items, source: :user

  before_save :capitalize_name

  def capitalize_name
    self.name = self.name.titleize
  end

  def self.search_by_name(search_term)
    return [] if search_term.blank?
    Product.where("name ILIKE ? ", "%#{search_term}%")
  end 

  def last_ordered
    orders.last.updated_at unless orders.empty?
  end

  def orders
    user_shopping_bag_items.where("position_type ILIKE ? ", Order).order('updated_at')
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController <AdminController

  def index
    @product = Product.new
    @products = Product.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "#{@product.name} was added"
      redirect_to admin_products_path
    else
      flash[:error] = "The product #{@product.name} was NOT added"
      @products = Product.all
      render :index
    end  
  end

  def edit
    @product = Product.find_by(slug: params[:id])
    @products = Product.all
    render :index
  end

  def update
    @product = Product.find_by(slug: params[:id])
    if @product.update_attributes(product_params)
      flash[:notice] = "#{@product.name} was updated"
      redirect_to admin_products_path
    else
      flash[:error] = "#{@product.name} was NOT updated"
      @products = Product.all
      render :index
    end
  end

  def destroy
    product = Product.find_by(slug: params[:id])
    product.delete
    flash[:notice] = "#{product.name} was deleted"
    redirect_to admin_products_path
  end

  def stock
    @products = Product.all.order('stock')
  end

  def update_stock
    @product = Product.find_by(slug: params[:id])
    if @product.update(stock: params[:stock])
      flash[:notice] = "#{@product.name} stock was updated"
    else
      flash[:error] = "Error: #{@product.name} stock was NOT updated"
    end
    @products = Product.all.order('stock')
    render :stock

  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :category_id, :description, :image, :stock, :sacred_symbol_ids => [])
  end

end

app/controllers/products_controller.rb
class ProductsController <ApplicationController

  def show
    @product = Product.find_by(slug: params[:id])
    @related_products = Product.all
  end

  def search
    @products = Product.search_by_name(params[:search_term]) 
    SacredSymbol.search_by_name(params[:search_term]).each do |sacred_symbol|
      @products += sacred_symbol.products.drop_while { |item| @products.include?(item) } 
    end
    Category.search_by_name(params[:search_term]).each do |category|
      @products += category.products.drop_while { |item| @products.include?(item) } 
    end
  end

end

app/views/products/_product.html.haml
.product-col
  .row
    .col-xs-12
      = link_to product_path(product) do
        .image    
          %img.img-responsive{:alt => "product", :src => product.image}/
    .col-xs-12.product-details
      .caption
        .product-name
          %h4
            = link_to product.name, product_path(product) 
        .price
          %span.price-new  #{display_price(product.price)}
        .bag-button.button-group
          = link_to user_wishlist_items_path(product_id: product.id), method: :post, class: 'btn btn-wishlist' do
            %i.fa.fa-heart
          = link_to user_shopping_bag_items_path(product_id: product.id, qty: 1), method: :post, class: 'btn btn-bag' do
            Add To Bag
            %img.shopping-bag{:alt => "Shopping Bag", :src => '/images/shopping_bag_sm.png' }

app/views/products/search.html.haml
.row
  / Primary Content Starts
  .col-md-9
    .products-list
      / Product Grid Display Starts
      .row
        - @products.each do |product|
          .col-sm-3.col-xs-6.product-responsive-padding
            = render 'products/product', :product => product
      / Product Grid Display Ends
  / Primary Content Ends
  .col-md-3
    = render 'shared/sidebar'
/ Main Container Ends

app/views/products/show.html.haml
.row
  / Primary Content Starts
  .col-md-9
    / Product Info Starts
    .row.product-info.full
      / Left Starts
      .col-sm-4.images-block
        .image
          %img.img-responsive{:alt => "Image", :src => @product.image }/
      / Left Ends
      / Right Starts
      .col-sm-8.product-details
        .panel-smart
          / Product Name Starts
          %h2   
            = @product.name
          / Product Name Ends
          %hr/
          / Manufacturer Starts
          %ul.list-unstyled.manufacturer
            %li
              %span Category:
              = link_to @product.category.name, category_path(@product.category)
            %li
              %span Sacred Symbol:
              - @product.sacred_symbols.each do |sacred_symbol|
                = link_to sacred_symbol.name, sacred_symbol_path(sacred_symbol)
            %li
              %span Availability:
              - if @product.stock <= 0
                %strong.label.label-danger Out Of Stock
              - else
                %strong.label.label-success In Stock
          / Manufacturer Ends
          %hr/
          / Price Starts
          .price
            %span.price-head Price :
            %span.price-new #{display_price(@product.price)}
          / Price Ends
          %hr/
          / Available Options Starts
          = form_tag user_shopping_bag_items_path, method: :post do
            .row 
              .col-sm-1
                = label_tag 'qty', 'QTY', class: 'control-label'
              .col-sm-2  
                = hidden_field_tag 'product_id', @product.id
                = number_field_tag 'qty', 1, class: 'form-control', min: 1
              .col-sm-6 
                .bag-button.button-group
                  = button_tag nil, class: 'btn btn-bag' do
                    Add To Bag
                    %img.shopping-bag{:alt => "Shopping Bag", :src => '/images/shopping_bag_sm.png' }
                  = link_to user_wishlist_items_path(product_id: @product.id), method: :post , class: 'btn btn-wishlist'do                    
                    %i.fa.fa-heart

          / Available Options Ends
      / Right Ends
    / Product Info Ends
    / Tabs Starts
    .tabs-panel.panel-smart
      / Nav Tabs Starts
      %ul.nav.nav-tabs
        %li.active
          %a{:href => "#tab-description", "data-toggle" => "tab"} Description
        %li
          %a{:href => "#tab-category-description", "data-toggle" => "tab"} #{@product.category.name} 
        %li
          %a{:href => "#tab-sacred_symbols", "data-toggle" => "tab"} Sacred Symbols
      / Nav Tabs Ends
      / Tab Content Starts
      .tab-content.clearfix
        / Description Starts
        #tab-description.tab-pane.active
          = @product.description
        / Description Ends
        / Category description Starts
        #tab-category-description.tab-pane
          %p
            = @product.category.description
        / Category Description Ends
        / Symbol Starts
        #tab-sacred_symbols.tab-pane
          - @product.sacred_symbols.each do |sacred_symbol|
            %h4
              = sacred_symbol.name
            = sacred_symbol.description  
        / Symbol Ends
      / Tab Content Ends
    / Tabs Ends
    / Related Products Starts
    .products-list
      %h2.product-head
        Similar Items
      / Products Row Starts
      .row
        -@related_products.each do |product|
          .col-sm-3.col-xs-6.product-responsive-padding 
            = render 'product', :product => product     
      / Products Row Ends
    / Related Products Ends
  .col-md-3
    = render 'shared/sidebar'  
  / Main Container Ends